### ISSUE TITLE
print msg error

### ISSUE THREAD

**Issue by yanir3** [aidanrt/twitch-bot#1]
error in functions_general.py -> print msg -> 'UnicodeEncodeError: 'charmap' codec can't encode character u'\u200b' in position 61: character maps to <undefined>'

I tried to use !randomemote.

**Comment by Aareon** [comment]
For future reference, adding .encode('utf-8') to msg fixes this error on non-ascii machines. Example;
```msg.encode('utf-8')```
I've created a pull request to make this an official patch.
